/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.View;

import javax.swing.*;
import mvc.Controller.ControllerJadwal;
/**
 *
 * @author HP
 */
public class FormJadwal extends javax.swing.JFrame {
    ControllerJadwal cbt;
    /**
     * Creates new form FormJadwal
     */
    public FormJadwal() {
        initComponents();
        cbt = new ControllerJadwal(this);
        cbt.isiTabel();
        cbt.isiComboGuru(nipGuru);
        cbt.isiComboKelas(kelasId);
        cbt.isiComboMataPelajaran(kodeMapel);
    }

    /**
     * @return the btnBackJadwal
     */
    public javax.swing.JButton getBtnBackJadwal() {
        return btnBackJadwal;
    }

    /**
     * @return the btnBatalJatwal
     */
    public javax.swing.JButton getBtnBatalJatwal() {
        return btnBatalJatwal;
    }

    /**
     * @return the btnCariHari
     */
    public javax.swing.JButton getBtnCariHari() {
        return btnCariHari;
    }

    /**
     * @return the btnHapusJadwal
     */
    public javax.swing.JButton getBtnHapusJadwal() {
        return btnHapusJadwal;
    }

    /**
     * @return the btnSimpanJadwal
     */
    public javax.swing.JButton getBtnSimpanJadwal() {
        return btnSimpanJadwal;
    }

    /**
     * @return the btnUbahJadwal
     */
    public javax.swing.JButton getBtnUbahJadwal() {
        return btnUbahJadwal;
    }

    /**
     * @return the carijadwal
     */
    public javax.swing.JComboBox<String> getCarijadwal() {
        return carijadwal;
    }

    /**
     * @return the dsnTabelJadwal
     */
    public javax.swing.JTable getDsnTabelJadwal() {
        return dsnTabelJadwal;
    }

    /**
     * @return the hari
     */
    public javax.swing.JComboBox<String> getHari() {
        return hari;
    }

    /**
     * @return the jFrame1
     */
    public javax.swing.JFrame getjFrame1() {
        return jFrame1;
    }

    /**
     * @return the jFrame2
     */
    public javax.swing.JFrame getjFrame2() {
        return jFrame2;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel10
     */
    public javax.swing.JLabel getjLabel10() {
        return jLabel10;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jLabel6
     */
    public javax.swing.JLabel getjLabel6() {
        return jLabel6;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @return the jLabel8
     */
    public javax.swing.JLabel getjLabel8() {
        return jLabel8;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @return the jRadioButton1
     */
    public javax.swing.JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the jadwalId
     */
    public javax.swing.JTextField getJadwalId() {
        return jadwalId;
    }

    /**
     * @return the jamMulai
     */
    public javax.swing.JFormattedTextField getJamMulai() {
        return jamMulai;
    }

    /**
     * @return the jamSelesai
     */
    public javax.swing.JFormattedTextField getJamSelesai() {
        return jamSelesai;
    }

    /**
     * @return the kelasId
     */
    public javax.swing.JComboBox<String> getKelasId() {
        return kelasId;
    }

    /**
     * @return the kodeMapel
     */
    public javax.swing.JComboBox<String> getKodeMapel() {
        return kodeMapel;
    }

    /**
     * @return the nipGuru
     */
    public javax.swing.JComboBox<String> getNipGuru() {
        return nipGuru;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBackJadwal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jadwalId = new javax.swing.JTextField();
        hari = new javax.swing.JComboBox<>();
        jamMulai = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsnTabelJadwal = new javax.swing.JTable();
        kelasId = new javax.swing.JComboBox<>();
        nipGuru = new javax.swing.JComboBox<>();
        kodeMapel = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        carijadwal = new javax.swing.JComboBox<>();
        btnSimpanJadwal = new javax.swing.JButton();
        btnUbahJadwal = new javax.swing.JButton();
        btnHapusJadwal = new javax.swing.JButton();
        btnBatalJatwal = new javax.swing.JButton();
        jamSelesai = new javax.swing.JFormattedTextField();
        btnCariHari = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("JADWAL MANAGEMEN SYSTEM");

        btnBackJadwal.setBackground(new java.awt.Color(153, 255, 255));
        btnBackJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnBackJadwal.setText("BACK");
        btnBackJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnBackJadwal)
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackJadwal))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Jadwal       :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Hari                 :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jam Mulai      :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Jam Selesai  :");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID Kelas         :");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NIP Guru       :");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kode Mapel  :");

        jadwalId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalIdActionPerformed(evt);
            }
        });

        hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Hari --", "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));
        hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariActionPerformed(evt);
            }
        });

        try {
            jamMulai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jamMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamMulaiActionPerformed(evt);
            }
        });

        dsnTabelJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dsnTabelJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsnTabelJadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsnTabelJadwal);

        kelasId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nipGuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        kodeMapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kodeMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeMapelActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Search (Hari) :");

        carijadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));
        carijadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carijadwalActionPerformed(evt);
            }
        });

        btnSimpanJadwal.setBackground(new java.awt.Color(153, 255, 255));
        btnSimpanJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnSimpanJadwal.setText("Simpan");
        btnSimpanJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanJadwalActionPerformed(evt);
            }
        });

        btnUbahJadwal.setBackground(new java.awt.Color(153, 255, 255));
        btnUbahJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnUbahJadwal.setText("Ubah");
        btnUbahJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahJadwalActionPerformed(evt);
            }
        });

        btnHapusJadwal.setBackground(new java.awt.Color(153, 255, 255));
        btnHapusJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnHapusJadwal.setText("Hapus");
        btnHapusJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusJadwalActionPerformed(evt);
            }
        });

        btnBatalJatwal.setBackground(new java.awt.Color(153, 255, 255));
        btnBatalJatwal.setForeground(new java.awt.Color(0, 0, 0));
        btnBatalJatwal.setText("Batal");
        btnBatalJatwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalJatwalActionPerformed(evt);
            }
        });

        try {
            jamSelesai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCariHari.setBackground(new java.awt.Color(153, 255, 255));
        btnCariHari.setForeground(new java.awt.Color(0, 0, 0));
        btnCariHari.setText("Cari");
        btnCariHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariHariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kodeMapel, 0, 138, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kelasId, 0, 138, Short.MAX_VALUE)
                            .addComponent(nipGuru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jadwalId))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(13, 13, 13))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jamMulai)
                                .addComponent(hari, 0, 133, Short.MAX_VALUE)
                                .addComponent(jamSelesai)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnSimpanJadwal)
                        .addGap(26, 26, 26)
                        .addComponent(btnUbahJadwal)
                        .addGap(31, 31, 31)
                        .addComponent(btnHapusJadwal)
                        .addGap(37, 37, 37)
                        .addComponent(btnBatalJatwal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(carijadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariHari)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jadwalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(carijadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariHari))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kelasId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nipGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kodeMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanJadwal)
                    .addComponent(btnUbahJadwal)
                    .addComponent(btnHapusJadwal)
                    .addComponent(btnBatalJatwal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jadwalIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalIdActionPerformed

    private void hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hariActionPerformed

    private void jamMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamMulaiActionPerformed

    private void btnSimpanJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanJadwalActionPerformed
        // TODO add your handling code here:
        String nip = cbt.getSelectedGuruNIP(nipGuru);
        String idkelas = cbt.getSelectedIdKelas(kelasId);
        String kodemapel = cbt.getSelectedKodeMapel(kodeMapel);
        
        cbt.insert(nip,idkelas,kodemapel);
        cbt.isiTabel();
        cbt.reset();
    }//GEN-LAST:event_btnSimpanJadwalActionPerformed

    private void btnCariHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariHariActionPerformed
        // TODO add your handling code here:
        cbt.carinama();
    }//GEN-LAST:event_btnCariHariActionPerformed

    private void btnUbahJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahJadwalActionPerformed
        // TODO add your handling code here:
        String nip = cbt.getSelectedGuruNIP(nipGuru);
        String idkelas = cbt.getSelectedIdKelas(kelasId);
        String kodemapel = cbt.getSelectedKodeMapel(kodeMapel);
        
        cbt.update(nip,idkelas,kodemapel);
        cbt.isiTabel();
        cbt.reset();
    }//GEN-LAST:event_btnUbahJadwalActionPerformed

    private void btnHapusJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusJadwalActionPerformed
        // TODO add your handling code here:
        cbt.delete();
        cbt.isiTabel();
        cbt.reset();
    }//GEN-LAST:event_btnHapusJadwalActionPerformed

    private void btnBatalJatwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalJatwalActionPerformed
        // TODO add your handling code here:
        cbt.reset();
    }//GEN-LAST:event_btnBatalJatwalActionPerformed

    private void kodeMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeMapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeMapelActionPerformed

    private void btnBackJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackJadwalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackJadwalActionPerformed

    private void carijadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carijadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carijadwalActionPerformed

    private void dsnTabelJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsnTabelJadwalMouseClicked
        // TODO add your handling code here:
        int row = dsnTabelJadwal.rowAtPoint(evt.getPoint());
        cbt.isiField(row);
    }//GEN-LAST:event_dsnTabelJadwalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJadwal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackJadwal;
    private javax.swing.JButton btnBatalJatwal;
    private javax.swing.JButton btnCariHari;
    private javax.swing.JButton btnHapusJadwal;
    private javax.swing.JButton btnSimpanJadwal;
    private javax.swing.JButton btnUbahJadwal;
    private javax.swing.JComboBox<String> carijadwal;
    private javax.swing.JTable dsnTabelJadwal;
    private javax.swing.JComboBox<String> hari;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jadwalId;
    private javax.swing.JFormattedTextField jamMulai;
    private javax.swing.JFormattedTextField jamSelesai;
    private javax.swing.JComboBox<String> kelasId;
    private javax.swing.JComboBox<String> kodeMapel;
    private javax.swing.JComboBox<String> nipGuru;
    // End of variables declaration//GEN-END:variables
}
